server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://postgres:5432/customer
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
    username: guest
    password: guest
#  cloud:
#    compatibility-verifier:
#      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    org.springframework.amqp: debug