server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#  cloud:
#    compatibility-verifier:
#      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true