spring:
  application:
    name: eureka-server
server:
  port: 8761
#  cloud:
#    compatibility-verifier:
#      enabled: false

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
